---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: tamic5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-recommender
  template:
    metadata:
      labels:
        app: vpa-recommender
    spec:
      serviceAccountName: vpa-recommender
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
      - name: recommender
        image: 192.1.6.82/tanzu/vpa-recommender:1.4.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - name: prometheus
          containerPort: 8942
        livenessProbe:
          httpGet:
            path: /health-check
            port: prometheus
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health-check
            port: prometheus
            scheme: HTTP
          periodSeconds: 10
          failureThreshold: 3
